Build: Make release script create CDN directory if missing
```
$ node build/release.js 3.0.1
Current version is 3.0.1-pre; generating release 3.0.1
(...)
Copying dist/jquery-migrate.js to CDN/jquery-migrate-3.0.1.js
Error: ENOENT: no such file or directory, open 'CDN/jquery-migrate-3.0.1.js'
    at Object.fs.openSync (fs.js:652:18)
```